import = ["~/.cache/wal/alacritty.yml"]
live_config_reload = true

[font]
size = 8.5

[font.normal]
family = "NotoSansM Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollHalfPageUp"
key = "K"
mods = "Alt|Shift"

[[keyboard.bindings]]
action = "ScrollHalfPageDown"
key = "J"
mods = "Alt|Shift"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "K"
mods = "Alt|Shift|Control"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "J"
mods = "Alt|Shift|Control"

[scrolling]
history = 100000

[window.padding]
x = 0
y = 0
