#!/bin/python
import atexit
import os
from pathlib import Path
import readline


state = os.environ.get(
    'XDG_STATE_HOME',
    os.path.expanduser('~/.local/state')
)

histfile = Path(
    state,
    "python/python_history"
)

histfile.parent.mkdir(exist_ok=True)

try:
    readline.read_history_file(histfile)
    # default history len is -1 (infinite), which may grow unruly
    readline.set_history_length(-1)
except FileNotFoundError:
    pass

atexit.register(readline.write_history_file, histfile)
