#!/bin/python
import atexit
import os
import readline
import sys
from pathlib import Path

state = os.environ.get(
    'XDG_STATE_HOME',
    os.path.expanduser('~/.local/state')
)

histfile = Path(
    state,
    "python/history"
)

histfile.parent.mkdir(exist_ok=True)

if sys.version_info <= (3, 13):
    try:
        readline.read_history_file(histfile)
        readline.set_history_length(-1)
    except FileNotFoundError:
        pass
    atexit.register(readline.write_history_file, histfile)
else:
    pass
