#!/bin/sh

export           MANPAGER="sh -c 'col -bx | bat -l man -p'"
export               LESS='-j.3 -QSRiPm '
export         MANROFFOPT='-c'
export          LESSKEYIN="${XDG_CONFIG_HOME}/sh/lesskey"
export       LESSHISTFILE="${XDG_STATE_HOME}/less/history"

mkdir "${LESSHISTFILE%/*}" 2>/dev/null && touch "${LESSHISTFILE}"
