[theme]
theme = "plain"
[icons]
icons = "awesome4"
[icons.overrides]
music = "🔊"
backlight_empty = "🌑"
backlight_1     = "🌘"
backlight_2     = "🌘"
backlight_3     = "🌘"
backlight_4     = "🌘"
backlight_5     = "🌗"
backlight_6     = "🌗"
backlight_7     = "🌗"
backlight_8     = "🌗"
backlight_9     = "🌖"
backlight_10    = "🌖"
backlight_11    = "🌖"
backlight_12    = "🌖"
backlight_13    = "🌖"
backlight_full  = "🌕"
[theme.overrides]
separator = ' '

[[block]]
block = "taskwarrior"
data_location = "${XDG_DATA_HOME}/taskwarrior"
interval = 60
format = "$icon $count $filter_name "
warning_threshold = 10
critical_threshold = 20
[[block.click]]
button = "left"
cmd = "alacritty -e zsh -c 'task && zsh -i'"
[[block.filters]]
name = "tasks"
filter = "+PENDING"

# [[block]]
# block = "music"
# dynamic_width = true
# marquee_interval = 10
# hide_when_empty = true
# buttons = ["prev", "play", "next"]
# format = "{combo}"
# [[block.click]]
# button = "left"
# cmd = "alacritty -e ncmpcpp"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
warning = 20.0
alert = 10.0
format = "$icon $available ($percentage.eng(w:1)) "

[[block]]
block = "memory"
format = "$icon $mem_used.eng(w:4) ($mem_used_percents.eng(w:1)) "
interval = 5
warning_mem = 80
critical_mem = 95

[[block]]
block = "cpu"
interval = 1
[[block.click]]
cmd = "alacritty -e zsh -ic htop"
button = "left"

[[block]]
block = "sound"

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "battery"
interval = 10
format = " $icon $percentage $time "

[[block]]
block = "time"
interval = 1
format = "$icon $timestamp.datetime(format:'%a %d/%m | %R:%S', locale:pt_BR) "

[[block]]
block = "net"
device = "wlp5s0"
format = "$speed_down.eng(p:K) $speed_up.eng(p:K) "
interval = 2
[[block.click]]
button = "left"
cmd = "alacritty -e zsh -ic 'sudo bandwhich'"

[[block]]
block = "custom"
command = '''nmcli -t connection | awk -F : '(NR == 1){ print $1 }''''
interval = 5
[[block.click]]
button = "left"
cmd = "alacritty -e zsh -ic 'sudo bandwhich'"

[[block]]
block = "bluetooth"
mac = "50:5B:C2:B4:4B:C8"
disconnected_format = ""
format = ""
