#!/bin/bash
# vim: foldmethod=marker
force_color_prompt=yes
set -o vi
set -o noclobber

# bash colors {{{
# Reset
OFF='\[\033[0m\]'       # Text Reset

# Bold
Bb='\[\033[1;30m\]'       # Black
BR='\[\033[1;31m\]'       # Red
BG='\[\033[1;32m\]'       # Green
BY='\[\033[1;33m\]'       # Yellow
BB='\[\033[1;34m\]'       # Blue
BP='\[\033[1;35m\]'       # Purple
BC='\[\033[1;36m\]'       # Cyan
BW='\[\033[1;37m\]'       # White
# }}}

# PS1 {{{
PS1=''
PS1+="${BC}\u${OFF}"
PS1+="@"
PS1+="${BR}\h${OFF}"
PS1+=": "
PS1+="${BG}\w${OFF}"
PS1+=" \$ "
# }}}

# history {{{
shopt -s histappend
HISTFILE="${XDG_STATE_HOME}/bash/history"
HISTSIZE=
HISTFILESIZE=
HISTCONTROL=ignoredups:erasedups:ignorespace
PROMPT_COMMAND="history -a; history -c; history -r"
HISTTIMEFORMAT='%d/%m/%y %H:%M  '
HISTIGNORE="ls:cd:q:c"
mkdir -pv "${HISTFILE%/*}" 2>/dev/null && touch "${HISTFILE}"
# }}}

aliasrc="${XDG_CONFIG_HOME}/sh/aliasrc"
[ -f "${aliasrc}" ] && source "${aliasrc}"

functions="${XDG_CONFIG_HOME}/sh/functions"
[ -f "${functions}" ] && source "${functions}"

alias h="history"

gpg-connect-agent updatestartuptty /bye &>/dev/null
export GPG_TTY="$(tty)"
