#!/bin/sh
[[ -f ~/.bash_profile ]] && source ~/.bash_profile

xset -b
xset r rate 500 30
setxkbmap -layout br -variant abnt2 -option caps:swapescape

xmodmap $FILES/kbd/qwerty.altgr
xrdb -merge $FILES/x/xresources

sleep 2 && hdmi on 17
exec i3
