#!/bin/sh
[[ -f ~/.bash_profile ]] && source ~/.bash_profile

xset -b
xset r rate 500 30
setxkbmap -layout br -variant abnt2 -option caps:swapescape

xset +fp $XDG_DATA_HOME/fonts
xset fp rehash

xmodmap $FILES/kbd/qwerty.altgr
xrdb -merge $FILES/x/xresources

sleep 2 && monon 9 9
exec i3
