#!/bin/zsh

source "${HOME}/.config/sh/profile"
source "${XDG_CONFIG_HOME}/sh/pagerrc"

export       HISTFILE="${XDG_STATE_HOME}/zsh/history"
export HISTORY_IGNORE="c|cl|q|exit|ls|l|la"
export       HISTSIZE="999999"
export       SAVEHIST="999999"
mkdir "${HISTFILE%/*}" 2>/dev/null && touch "${HISTFILE}"

if [ "$(tty)" = '/dev/tty1' ]; then
	exec startx "${XINITRC}" &>/dev/null
fi
