runtime user/highlighting.vim
runtime user/goyo.vim
runtime user/coc.vim
runtime user/nerdtree.vim
runtime user/undotree.vim
runtime user/limelight.vim
runtime user/tex.vim
runtime user/statusline.vim
runtime user/function.vim
runtime user/maps.vim
