#!/bin/sh
# vim: foldmethod=marker
force_color_prompt=yes
set -o noclobber
stty -ixon

# bash colors {{{
# Reset
OFF='\[\033[0m\]'       # Text Reset

# Bold
Bb='\[\033[1;30m\]'       # Black
BR='\[\033[1;31m\]'       # Red
BG='\[\033[1;32m\]'       # Green
BY='\[\033[1;33m\]'       # Yellow
BB='\[\033[1;34m\]'       # Blue
BP='\[\033[1;35m\]'       # Purple
BC='\[\033[1;36m\]'       # Cyan
BW='\[\033[1;37m\]'       # White
# }}}

# PS1 {{{
PS1=''
PS1+="${BC}\u${OFF}"
PS1+="@"
PS1+="${BR}\h${OFF}"
PS1+=": "
PS1+="${BG}\w${OFF}"
PS1+=" \$ "
# }}}

function pass() { # {{{
	clipctl disable
	PASSWORD_STORE_GENERATED_LENGTH=12 /usr/bin/pass $@
	clipctl enable
}
# }}}

source "$XDG_CONFIG_HOME/sh/aliasrc"

[ -z "${VIM_TERMINAL}" ] && (cat "$HOME/.cache/wal/sequences" 2>/dev/null &)

gpg-connect-agent updatestartuptty /bye &>/dev/null
export GPG_TTY="$(tty)"
