#!/bin/bash
# vim: foldmethod=marker

source "${HOME}/.config/sh/profile"
source "${XDG_CONFIG_HOME}/sh/pagerrc"
source "${XDG_CONFIG_HOME}/bash/bashrc"

# history {{{
shopt -s histappend
export       HISTFILE="${XDG_STATE_HOME}/bash/history"
export       HISTSIZE=
export   HISTFILESIZE=
export    HISTCONTROL=ignoredups:erasedups:ignorespace
export PROMPT_COMMAND="history -a; history -c; history -r"
export HISTTIMEFORMAT='%d/%m/%y %H:%M  '
export     HISTIGNORE="ls:cd:q:c"
mkdir -pv "${HISTFILE%/*}" 2>/dev/null && touch "${HISTFILE}"
# }}}
