#!/bin/bash

# hist options
shopt -s histappend
export HISTSIZE=
export HISTFILESIZE=
export HISTCONTROL=ignoredups:erasedups:ignorespace
export PROMPT_COMMAND="history -a; history -c; history -r"
export HISTTIMEFORMAT='%d/%m/%y %H:%M  '
export HISTIGNORE="ls:cd:q:c"

# less options
export LESSOPEN="| /usr/bin/source-highlight-esc.sh %s"
export LESS=-Ri
export LESSHISTFILE=-
export LESS_TERMCAP_mb=$'\E[1;31m'     # begin blink
export LESS_TERMCAP_md=$'\E[1;36m'     # begin bold
export LESS_TERMCAP_me=$'\E[0m'        # reset bold/blink
export LESS_TERMCAP_us=$'\E[1;32m'     # begin underline
export LESS_TERMCAP_ue=$'\E[0m'        # reset underline

# export options
export PATH="$PATH":"$HOME"/bin:"$HOME"/.local/bin
export XDG_DATA_HOME="$HOME"/.local/share
export XDG_CACHE_HOME="$HOME"/.cache
export XDG_CONFIG_HOME="$HOME"/.config
export FILES="$HOME"/.files
#
export VIMINIT=":source $XDG_CONFIG_HOME"/vim/vimrc.vim
export XINITRC="$XDG_CONFIG_HOME"/x/xinitrc
export ZDOTDIR="$XDG_CONFIG_HOME"/zsh
export ELECTRUMDIR="$XDG_CONFIG_HOME"/electrum
export GNUPGHOME="$XDG_CONFIG_HOME"/gpg
export PASSWORD_STORE_DIR="$XDG_CONFIG_HOME"/pass
#
export IPYTHONDIR="$XDG_CONFIG_HOME"/ipython
export PYTHONSTARTUP="$XDG_CONFIG_HOME"/python/pythonrc
export JUPYTER_CONFIG_DIR="$XDG_CONFIG_HOME"/jupyter
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME"/npm/npmrc
export CARGO_HOME="$XDG_CONFIG_HOME"/cargo
export RUSTUP_HOME="$XDG_CONFIG_HOME"/rustup
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java
#
export XAUTHORITY="$XDG_CACHE_HOME"/Xauthority
export HISTFILE="$XDG_CACHE_HOME"/bash/history
#
export FONTS="$XDG_DATA_HOME"/fonts:/usr/share/fonts
#
export EDITOR=vim
export BROWSER=firefox
export TERM=alacritty

# xinit
alias startx="startx $XINITRC &>/dev/null"
[ -f "$HOME"/.bashrc ] && source ~/.bashrc
[ "$(tty)" = '/dev/tty1' ] && startx
